### ISSUE TITLE
InputNumber组件优化建议

### ISSUE THREAD

**Issue by SyanH** [lewkamtao/lew-ui#105]
目前InputNumber组件右侧增加和减少按钮感觉有点不协调，能否换成上下箭头图标
还有这个图标按钮能否只有hover的时候才显示

**Comment by lewkamtao** [comment]
hi，很高兴你提出的建议，第一个我觉得提的很好，可以改来看看，但是第二点可能如果只有 hover的时候显示的话，那么他是 input的样子，我认为可能没有辨识度，可能没那么好。

**Comment by SyanH** [comment]
第二条说的也有道理🤔️
