### ISSUE TITLE
个人的一些小建议

### ISSUE THREAD

**Issue by AAABingBing** [lewkamtao/lew-ui#117]
- 建议使用 rem 代替 px，以提供更好的一致性

> [PrimeVue](https://primevue.org/)
> [Shadcn](https://ui.shadcn.com/)
> [Please stop using px for font-size.](https://www.youtube.com/watch?v=xCSw6bPXZks)

- 期待添加 unplugin-vue-components 和 unplugin-auto-import Resolver 支持

**Comment by lewkamtao** [comment]
很好，我去研究研究，感谢～

**Comment by lewkamtao** [comment]
这个我研究了一下，发现工作量不小，因为现在有的插件只能批量的把css的px转成rem，但内联的样式就没办法转化，这个可能得整体改造成rem，而不是用转化的方式；可能delay一段时间，现在又更加重要的东西需要完善哈哈哈

**Comment by AAABingBing** [comment]
> 这个我研究了一下，发现工作量不小，因为现在有的插件只能批量的把css的px转成rem，但内联的样式就没办法转化，这个可能得整体改造成rem，而不是用转化的方式；可能delay一段时间，现在又更加重要的东西需要完善哈哈哈

感谢回复
