### ISSUE TITLE
Badge组件的数字貌似没有上下居中

### ISSUE THREAD

**Issue by coderwang267** [lewkamtao/lew-ui#118]
![image](https://github.com/user-attachments/assets/00f5b611-a2c7-4fde-b2ec-5cb0c12251b1)
如图

**Comment by AnYiEE** [comment]
应该是因为`.lew-badge-value`没指定高度。

**Comment by lewkamtao** [comment]
谢谢啦～我一直以为是字体的缘故 没认真看，我来优化一下～

**Comment by lewkamtao** [comment]
这个我确认了，不是没指定高度，似乎就是字体的问题，其实在mac上面是很居中的，应该是微软雅黑的问题。

**Comment by AnYiEE** [comment]
> 这个我确认了，不是没指定高度，似乎就是字体的问题，其实在mac上面是很居中的，应该是微软雅黑的问题。

加个height: auto。

**Comment by lewkamtao** [comment]
我刚刚加了line-height: 18px; 就正常了，如果高度是auto，那么当一个数字的时候，就不是一个圆了。

**Comment by AnYiEE** [comment]
> 我刚刚加了line-height: 18px; 就正常了，如果高度是auto，那么当一个数字的时候，就不是一个圆了。

那你应该用min-height和min-width，加上justify-content: center。

**Comment by lewkamtao** [comment]
已在新版本修复该缺陷
