### ISSUE TITLE
设置网页底部的 .footer 样式之后会导致 Popok 组件下的 .footer 样式受影响

### ISSUE THREAD

**Issue by nanxuanmoke** [lewkamtao/lew-ui#122]
因为使用 Bootstrap 美化主题 Tabler，该主题默认对 .footer 设置了样式。

结果导致 lew-ui 的 Popok 组件 .footer 受影响，影响样式。

![图片](https://github.com/user-attachments/assets/68f0b122-03b4-42f7-b3a2-77b809d09cd1)
![图片](https://github.com/user-attachments/assets/6c8083ab-7bad-49bc-9d88-ebea4a350c42)
![图片](https://github.com/user-attachments/assets/dd42f76b-4334-403f-9659-66e5c4873d49)

**Comment by lewkamtao** [comment]
好的，我需要调整一下这些比较公共的类名，加上一些前缀。

**Comment by nanxuanmoke** [comment]
> 好的，我需要调整一下这些比较公共的类名，加上一些前缀。

刚发现 Modal 组件也受影响了。

**Comment by nanxuanmoke** [comment]
> 好的，我需要调整一下这些比较公共的类名，加上一些前缀。

同样也是.footer

**Comment by lewkamtao** [comment]
更新一下 "version": "2.4.3" 版本，我解决了这个问题。
