### ISSUE TITLE
【BUG】给lew-table设置高度之后，会导致空数据提示挤到底部

### ISSUE THREAD

**Issue by nanxuanmoke** [lewkamtao/lew-ui#123]
给lew-table设置高度，以达到超出内容显示滚动条的效果，结果出现意外，空数据图标会被挤到底部。

![图片](https://github.com/user-attachments/assets/54a8474b-6e6d-47c7-bb0c-da185ebc0f66)
![图片](https://github.com/user-attachments/assets/742c423e-0667-4f34-b61f-47573040352f)
![图片](https://github.com/user-attachments/assets/823729b4-0022-451b-9fca-56b403c24bbc)

添加如下样式，恢复正常：
position: absolute;
top: 50%;
transform: translateY(-50%);

![图片](https://github.com/user-attachments/assets/32951719-058d-4c5b-a0d9-a0796ddb7cff)
![图片](https://github.com/user-attachments/assets/0534657d-736a-4377-8168-ede6e9fbe690)

**Comment by nanxuanmoke** [comment]
如果使用max-height则不会出现该问题，刚发现的。
槽点挺多，不会UI很好看，想继续用下去。🥲

**Comment by lewkamtao** [comment]
本身 lew-table 提供了 props max-height， 可以试试

**Comment by nanxuanmoke** [comment]
![图片](https://github.com/user-attachments/assets/66259f94-c2e9-4493-b9b0-ac69dd77bd97)


> 本身 lew-table 提供了 props max-height， 可以试试

老哥，你示例代码也是这么写的，示例代码就存在这个问题。

**Comment by lewkamtao** [comment]
我知道什么问题了，我修复一下。

**Comment by nanxuanmoke** [comment]
> 更新一下 "version": "2.4.3" 版本，我解决了这个问题。

感谢大哥，辛苦了。
