### ISSUE TITLE
【问题】我发现在lew-drawer组件内部使用lew-image的时候图片可以放大但是缺少了关闭切换这些按钮

### ISSUE THREAD

**Issue by Yuixiaoyu** [lewkamtao/lew-ui#129]
![image](https://github.com/user-attachments/assets/280e671b-2663-45fd-872d-1de1e2aa5824)
点开预览之后缺少了下面这些内容
![image](https://github.com/user-attachments/assets/c7d67b2e-d85d-4b1d-a537-9ca18348d683)
希望作者可以抽时间修复一下✌️

**Comment by lewkamtao** [comment]
已经定位到问题！下一个版本会更新。

**Comment by lewkamtao** [comment]
最新版本 已修复
