### ISSUE TITLE
[功能请求] 希望增加一个 admin layout  组件

### ISSUE THREAD

**Issue by InfernalAzazel** [lewkamtao/lew-ui#133]
类似效果

[admin layout](https://infernalazazel.github.io/k-naiveui-pro/cn/layout/)

![image](https://github.com/user-attachments/assets/904d8de6-2ecb-4d38-bc79-2516f0dc24c9)

**Comment by lewkamtao** [comment]
后续会推出一个admin的项目用于快速搭建后台

**Comment by InfernalAzazel** [comment]
> 后续会推出一个admin的项目用于快速搭建后台

admin 的项目开源社区太多了，也有通用的缺点功能太多的，还是需要删删改改来符合企业或者团队的编码标准，精简的admin curd 功能有需要自行开发。

有基础的组件是最好的。

要是作者没有空的 后门 layout 出来 我可以pr 这个  admin layout ，这个组件可以叫做 applayout。
