### ISSUE TITLE
【Cascader】功能/改进请求，问题咨询

### ISSUE THREAD

**Issue by ydq** [lewkamtao/lew-ui#135]
Cascader 目前不支持搜索，且底部的层级下拉框宽度强制为200，总宽也强制固定了(根据层级数 x 200）

用CSS强制覆盖也会存在一些问题，当遇到一些特殊的数据，如 长度稍长，且前缀都一样的情况下，无法很好的区分数据，只能鼠标悬浮一个个的看

如果能支持**自定义宽度** 或 者能支持每个层级下单独**模糊搜索**就很赞了。

---

另外Cascader使用异步加载，不知道是我使用有问题 还是什么，root层级填充之后，当手动给上一层级设置了children，好像并不生效，每次都会重新加载，请教一下如何处理比较合适

```js
const loadData = async item => {
    try {
        if (!item) {// 加载根层级
            const dbs = await getAllDatabases()
            return dbs.map(db => {
                return {
                    value: db,
                    label: db,
                    isLeaf: false
                }
            })
        }
        if(item.children?.length){ //step2：每次进来  还是为空 导致每次都要重新加载，请问该如何避免和优化呢？难道得自己维护一份本地数据，然后在 本地通过 item 过滤找到本地的缓存吗？
            return item.children
        }
        const tables = await getAllTableByDatabaseName(item.value)
        const children =  tables.sort().map(table => {
            return {
                value: `${item.value}.${table}`,
                label: table,
                isLeaf: true
            }
        })
        item.children = children //step1：这里给设置过了
        return children;
    } catch (e) {
        LewMessage.error({
            content: `获取信息失败:${e.message}`,
            duration: 3000
        })
    }
}
```

**Comment by lewkamtao** [comment]
第一点：我看看怎么优化；
第二点：https://lew.kamtao.com/#/Cascader，文档里面有一个异步加载的demo, loadMethod能接收一个Promise，返回对应的children,你只需要处理这个函数即可。

**Comment by ydq** [comment]
> 第一点：我看看怎么优化； 第二点：[https://lew.kamtao.com/#/Cascader，文档里面有一个异步加载的demo](https://lew.kamtao.com/#/Cascader%EF%BC%8C%E6%96%87%E6%A1%A3%E9%87%8C%E9%9D%A2%E6%9C%89%E4%B8%80%E4%B8%AA%E5%BC%82%E6%AD%A5%E5%8A%A0%E8%BD%BD%E7%9A%84demo), loadMethod能接收一个Promise，返回对应的children,你只需要处理这个函数即可。

@lewkamtao  官网的 异步 demo 也使每次都请求呢
![async](https://github.com/user-attachments/assets/0dbeb22b-4690-49cf-a428-4ced94280c28)

**Comment by lewkamtao** [comment]
哦哦，ok 我明白你的意思了，请求过的数据，我这边做一个map存储，不再触发loadMethod。
