### ISSUE TITLE
fancyapps并不是开源项目

### ISSUE THREAD

**Issue by varHarrie** [lewkamtao/lew-ui#137]
<img width="864" alt="image" src="https://github.com/user-attachments/assets/4ebc4cb3-db54-4eb6-8802-04a0e846e002">
https://fancyapps.com/pricing/

**Comment by lewkamtao** [comment]
感谢提醒，我一直以为基础的功能是免费的，没留意到这个，我马上剔除掉这个插件，感谢！！！！

**Comment by lewkamtao** [comment]
已经在最新的版本移除了fancyapps

**Comment by lewkamtao** [comment]
感谢哈哈哈
