### ISSUE TITLE
【建议】统一 input / button 的相同size的高度

### ISSUE THREAD

**Issue by ydq** [lewkamtao/lew-ui#140]
目前使用Chrome 测量两个组件高度
|组件|small|medium|large|
|---|---|---|---|
|button|30|34|38|
|input|33|37|41|

因为 lew 没有直接提供类似于  input + button 这样的 “input-group” 组合组件，当自己直接使用这俩组件的时候发现高度不一致，有点难受，希望能改进一下

<img width="309" alt="image" src="https://github.com/user-attachments/assets/cd73a8ed-4b55-493f-be6f-45f056193dcb" />
<img width="645" alt="image" src="https://github.com/user-attachments/assets/d92cbe3b-8f84-4768-b5bf-2719a73ec862" />

<img width="353" alt="image" src="https://github.com/user-attachments/assets/6a7d337f-d160-4499-8a0b-7e48d04fb3cf" />
<img width="517" alt="image" src="https://github.com/user-attachments/assets/24eb6b5e-4b7c-47e2-a542-b33551624fed" />

**Comment by lewkamtao** [comment]
好 我调整一下

**Comment by lewkamtao** [comment]
"version": "2.5.1" 已优化这个问题
