### ISSUE TITLE
【功能请求】input 组件 不满足 Chrome Extension CSP，期待改进

### ISSUE THREAD

**Issue by ydq** [lewkamtao/lew-ui#141]
貌似因为最终生成的HTML中有这么一句 inline-script:
> onkeypress="if(window.event.keyCode==13) this.blur()"

<img width="650" alt="image" src="https://github.com/user-attachments/assets/3d2bcbb8-01bf-442f-b65b-e9540b103d80" />

---

题外话：

- 向大佬请教一下，为什么 lew-ui 的事件设计上 好多都使用 属性的方式绑定(通过:xxx而不是 @xxx)，不是专业前端，真心求学。
- 另外是不是也可以定制部分组件的属性/事件 的继承节点，比如 lew-input 最后渲染的dom节点是 div 包裹 input，这样比如 想给 input 主动添加一些 html5 的特殊属性的时候（如 inputmode、enterkeyhint、pattern 等）无法直接在组件上添加，目前只能通过等挂载渲染好了 强行通过 js 来修改调整，感觉很多组件如果能根据具体的场景支持 属性/事件的自由继承，会不会更方便一些

**Comment by lewkamtao** [comment]
这是我微信 X0thbXRv (base64 解码) 有什么问题，可以加我，有时候 Github 回复不是很及时。

**Comment by ydq** [comment]
✅ fixed in 2.5.3
