### ISSUE TITLE
Pagination的pageSize改成小于pageShowSize的值有bug

### ISSUE THREAD

**Issue by kitiho** [lewkamtao/Lew-UI#23]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/51785099/181158609-4ddb6713-83e8-4daa-96db-a5a26ab8a14d.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/51785099/181158676-a7124bb7-1aca-4aa0-b512-023d7322f6c0.png">

**Comment by lewkamtao** [comment]
已修复
