### ISSUE TITLE
Table组件不显示滚动条，无法正常进行横向滚动

### ISSUE THREAD

**Issue by sechi747** [lewkamtao/Lew-UI#27]
![image](https://user-images.githubusercontent.com/73569598/181422498-c694af98-4d6e-4a8a-8e5c-a6f090d3658e.png)
![image](https://user-images.githubusercontent.com/73569598/181422695-cd4c8b98-74bb-45f4-be07-a7989a576f16.png)
不知道这里本来就是这么设计的还是怎么回事，加上一点高度就可以了

**Comment by lewkamtao** [comment]
谢谢提醒，其实原本是有的，但是后来觉得不够简洁就去掉了，如果有需要，那还是加回来好一些。

**Comment by lewkamtao** [comment]
已修复
