### ISSUE TITLE
非常喜欢你 的 图片 播放组件，你能留个联系方式嘛，或者建立一个群，真的好喜欢谢谢

### ISSUE THREAD

**Issue by huaxiaobao** [lewkamtao/Lew-UI#34]
非常喜欢你 的 图片 播放组件，你能留个联系方式嘛，或者建立一个群，真的好喜欢谢谢

**Comment by lewkamtao** [comment]
你可以联系我邮箱，然后我给你留个微信。

**Comment by huaxiaobao** [comment]
非常感谢您，我先给您留一个 我的微信 18843229775&nbsp; ，我怕到时候找不到您
这个 ui 的风格 我挺喜欢的，如果有机会，很想 加入 大佬 您这个团队，和团队&nbsp; 多多学习，虽然我还是个小菜鸡！




花小宝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lewkamtao/Lew-UI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上6:44
***@***.***&gt;;
抄送:&nbsp;"great    ***@***.******@***.***&gt;;
主题:&nbsp;Re: [lewkamtao/Lew-UI] 非常喜欢你 的 图片 播放组件，你能留个联系方式嘛，或者建立一个群，真的好喜欢谢谢 (Issue #34)





 
你可以联系我邮箱，然后我给你留个微信。
