### ISSUE TITLE
textarea缩放不跟手

### ISSUE THREAD

**Issue by Ealrang** [lewkamtao/Lew-UI#4]
textarea缩放不跟手，是故意这样设计的吗？

**Comment by denglouhen** [comment]
缩放可以不加动画，确实不跟手显得很迟钝

**Comment by lewkamtao** [comment]
感谢，已修复

**Comment by lewkamtao** [comment]
了解了 我修一下，可能加了过渡



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 闻畅 ***@***.***&gt;
发送时间: 2022年6月30日 09:05
收件人: lewkamtao/Lew-UI ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [lewkamtao/Lew-UI] textarea缩放不跟手 (Issue #4)
