### ISSUE TITLE
Tag 垂直不居中

### ISSUE THREAD

**Issue by TianQian-A** [lewkamtao/Lew-UI#5]
看了下 CSS，height 是 22px，lineHeight 是 13px，应该是这个原因导致的

**Comment by TianQian-A** [comment]
Button 也是类似的情况，不居中

**Comment by lewkamtao** [comment]
有没有截图，我这边正常哦

**Comment by TianQian-A** [comment]
> 有没有截图，我这边正常哦

Button 正常了，加上了 lineHeight。
Tag 如图
![Snipaste_2022-06-30_17-16-54](https://user-images.githubusercontent.com/38515093/176640961-2c973651-7efa-40b4-8e55-17c93b8a2cb5.png)

**Comment by lewkamtao** [comment]
可能是浏览器的兼容问题，你用的是啥浏览器，我又修复了一下

**Comment by TianQian-A** [comment]
Chrome for Windows 版本 102.0.5005.115（正式版本） （64 位）
目前正常了哈
