### ISSUE TITLE
不支持nuxt吗

### ISSUE THREAD

**Issue by murongg** [lewkamtao/lew-ui#50]

**Comment by lewkamtao** [comment]
理论上应该支持才对，我还没测试过，我有空测试一下，nuxt3应该支持，不过nuxt3现在还是beta。

**Comment by murongg** [comment]
> 理论上应该支持才对，我还没测试过，我有空测试一下，nuxt3应该支持，不过nuxt3现在还是beta。

进入 RC 了，我测试了，`message` 和 `notice` 等组件，这种有强依赖操作 DOM 需求的组件，不支持 nuxt3 的 ssr 模式。
还有就是貌似组件库没有打包类型文件。

**Comment by murongg** [comment]
并且 vscode 会抛出这个错误

```
import Lew from "lew-ui";

文件“/Users/xxx/nuxt-app/node_modules/.pnpm/lew-ui@1.1.3/node_modules/lew-ui/dist/lew.umd.ts”不是模块。ts(2306)
```

**Comment by lewkamtao** [comment]
可能是全局引入有点问题，我最近也在用，等我修好了 给你留言 抱歉老哥

**Comment by lewkamtao** [comment]
https://github.com/lewkamtao/lew-ui-nuxt3-template

您可以看看这个demo

**Comment by roonie007** [comment]
> https://github.com/lewkamtao/lew-ui-nuxt3-template
> 
> 您可以看看这个demo

@lewkamtao, the link is no longer working

**Comment by lewkamtao** [comment]
> > https://github.com/lewkamtao/lew-ui-nuxt3-template
> > 您可以看看这个demo
> 
> @lewkamtao, the link is no longer working

Try again, I forgot to enable permissions.
