### ISSUE TITLE
字体哪里弄的，源码怎么没找到

### ISSUE THREAD

**Issue by warmthsea** [lewkamtao/lew-ui#53]
![image](https://user-images.githubusercontent.com/45450994/196832111-33ff15aa-25cb-418e-86a0-59fd4ecfe076.png)

**Comment by lewkamtao** [comment]
@import url('https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css');
* {
    font-family: HarmonyOS_Regular, Helvetica Neue, Microsoft YaHei, sans-serif;
}

**Comment by lewkamtao** [comment]
@import url('https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css');

**Comment by warmthsea** [comment]
> @importurl(' https://s1.hdslb.com/bfs/static/jinkela/long/font/regular.css ');

谢谢
