### ISSUE TITLE
按需引入组件的时候，vue发出了警告

### ISSUE THREAD

**Issue by 2113ic** [lewkamtao/lew-ui#57]
我使用的组件是：LewInputPro
当我安装指南推荐的按需引入组件的时候，vue发出了警告。
当我使用全局注册所有组件时就会正常运行。

我的依赖：
- "lew-ui": "^1.1.24"
- "vue": "^3.2.45"

![image](https://user-images.githubusercontent.com/69682691/205429755-06ff7ef9-c0ef-4be8-902f-2301419f49c2.png)

**Comment by 2113ic** [comment]
> 解决了嘛？

似乎并没有，例如：dropdown 组件中依赖 popover 组件，但并没有显式引入该组。这种情况只有用户全局注册所有组件才不会报错。

**Comment by lewkamtao** [comment]
天哪！！我才发现，我今晚修复这个问题！！

**Comment by lewkamtao** [comment]
天哪！！我才发现，我今晚修复这个问题！！

**Comment by lewkamtao** [comment]
> 我使用的组件是：LewInputPro 当我安装指南推荐的按需引入组件的时候，vue发出了警告。 当我使用全局注册所有组件时就会正常运行。
> 
> 我的依赖：
> 
> * "lew-ui": "^1.1.24"
> * "vue": "^3.2.45"
> 
> ![image](https://user-images.githubusercontent.com/69682691/205429755-06ff7ef9-c0ef-4be8-902f-2301419f49c2.png)

这个InputPro被我废弃了，相关功能集成到了Input

**Comment by lewkamtao** [comment]
已修复！

**Comment by lewkamtao** [comment]
v1.5.11 的版本更新了这个问题。
