### ISSUE TITLE
单击模态窗口的遮罩会被强制关闭

### ISSUE THREAD

**Issue by yulon** [lewkamtao/lew-ui#59]
我发现新版本 `LewModal.vue` 中的 [maskClick](https://github.com/lewkamtao/lew-ui/commit/c7fcda90caaf29b14ba1788b8c80da3df9513e4a#diff-c8c8c4b2f704fe347cd65e2b05f161d384f8d99ab311900f06cfcd05a730636dR43) 会强制关闭模态窗口。

比如
```
:visible="show"
@mask-click="show = false"
```
新版本如果不写 `mask-click`，`show` 的值无法恢复成 `false`，导致必须写 `mask-click`，但又无法设置成点击遮罩不关闭。
而旧版本是不写 `mask-click` 就默认不关闭，写了 `mask-click` 就通过修改变量来关闭。

可以修改成和旧版本一样，或者增加个 `close-on-click-overlay` 属性吗？
因为不知道具体设计意图，我也不太清楚哪个比较好，就没有直接提 PR 了。

对于一些用于编辑数据的模态窗口，我认为还是点击遮罩不关闭比较好一点。

**Comment by lewkamtao** [comment]
hi，谢谢你的建议哈，前段时间太忙了，公司忙不过来，实在不好意思，我今晚看看优化一下。

**Comment by lewkamtao** [comment]
这个问题我看了，我会增加一个close的事件，然后新增这个属性close-on-click-overlay，另外加v-model:visible，可以直接双向绑定。

**Comment by lewkamtao** [comment]
这个问题已经解决啦~
