### ISSUE TITLE
1.0.18 版本发的包是不是有问题

### ISSUE THREAD

**Issue by TMaize** [lewkamtao/Lew-UI#6]
```
import 'lew-ui/dist/style.css'
```

https://unpkg.com/browse/lew-ui@1.0.18/dist/

![FCDE3DC2-FB4F-43b6-B2C7-48D7EF6B12D9](https://user-images.githubusercontent.com/16556693/176806830-52e8826c-0233-4dec-8dee-4dfd0bee110e.png)

**Comment by lewkamtao** [comment]
不是这样用的，你直接npm i lew-ui，这个是文档包。

**Comment by lewkamtao** [comment]
哦哦
我发现了 我打包的失误 抱歉，谢谢你的提醒

**Comment by lewkamtao** [comment]
已修复 你看看行不行

**Comment by lewkamtao** [comment]
1.0.18的版本，已废弃，谢谢兄弟了。😊
