### ISSUE TITLE
Textarea缩放问题

### ISSUE THREAD

**Issue by Ealrang** [lewkamtao/lew-ui#70]
1.2版本左右缩放不对劲

1. 左右缩放框不对
2. 缩放图标在字数限制上时候会选不到缩放图标

**Comment by lewkamtao** [comment]
谢谢您的反馈，我刚看了一下，的确有点问题，我有空处理一下。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Apr 29, 2023 11:17 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[lewkamtao/lew-ui] Textarea缩放问题 (Issue #70)

&nbsp;



 
1.2版本左右缩放不对劲
  
左右缩放框不对
 
缩放图标在字数限制上时候会选不到缩放图标
