### ISSUE TITLE
关于我提交代码时候遇到了大量eslint报错的这件事

### ISSUE THREAD

**Issue by 2113ic** [lewkamtao/lew-ui#81]
不知道是不是我的问题，我在提交代码的时候遇到了大量的eslint报错：

![image](https://github.com/lewkamtao/lew-ui/assets/69682691/4531e694-4af0-40c3-a96d-519cefb833cb)

上面截图只是一部分。

**Comment by lewkamtao** [comment]
我最近在重构这里的ts，不是很规范，等我哈哈哈

**Comment by 2113ic** [comment]
> 我最近在重构这里的ts，不是很规范，等我哈哈哈

是否可以考虑一下把 tabwidth 该为 2 个 space 呢？例如下面 vite.config.ts 这样看起来很不美观
![image](https://github.com/lewkamtao/lew-ui/assets/69682691/314ecc01-1d4b-485e-8562-2fce832d909e)

**Comment by lewkamtao** [comment]
已修复
