### ISSUE TITLE
import 'lew-ui/dist/style.css' error

### ISSUE THREAD

**Issue by Huelse** [lewkamtao/lew-ui#82]
```
[plugin:vite:import-analysis] Missing "./dist/style.css" specifier in "lew-ui" package
```
seems to not support by the latest vite? change to `import '/node_modules/lew-ui/dist/style.css'` will work.
[reproduce link](https://codesandbox.io/p/sandbox/damp-https-6ly8hl)

**Comment by lewkamtao** [comment]
import "lew-ui/style";

Sorry, the latest version has updated the import method.

**Comment by Huelse** [comment]
By the way, there is a warning: `[vite] warning: @vnode-* hooks in templates are deprecated. Use the vue: prefix instead. For example, @vnode-mounted should be changed to @vue:mounted. @vnode-* hooks support will be removed in 3.4.`
